---
output: ioslides_presentation
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      fig.width = 10,
                      fig.asp = 0.618,
                      fig.align = "center")


# read in the data, and organize it into a tidy format

library(tidyverse)
library(stringr)
library(modelr)

demos <- read_csv("demos.csv")

test <- read_csv("test_scores.csv")

# actually some of the items in demos and others are related
# to discipline, so we should extract those
demos_tidy <- demos %>% 
  slice(1:7) %>% 
  gather(year, value, 2:5) %>% 
  rename(category = X1) %>% 
  mutate(value = str_extract(value, "[0-9]+"),
         pct = as.numeric(value) * .01) # extract the percentages

# add in a total students for each year
total <- demos_tidy %>% 
  filter(str_detect(category, "Total")) %>% 
  select(-category,
         -pct,
         total = value) %>% 
  mutate(total = as.numeric(total))

# and then multiply by percent to give the number in each category

demos_tidy <- demos_tidy %>% 
  filter(!str_detect(category, "Total")) %>% 
  left_join(total, by = "year") %>% 
  mutate(count = total * pct,
         category = str_replace(category, "% ", ""),
         category = recode(category, 
                           "Students as English Language Learners" = "ELLs",
                           "Students with Disabilities" = "IEP")) %>% 
  select(-value)

# now moving on to outcomes/test scores
out <- test %>% 
  gather(year, pct, 3:6) %>% 
  mutate(subj = str_extract(`Academic Years`, "reading|math"),
         pct = as.numeric(str_replace(pct, "%", "")) * .01) %>% 
  select(-`Academic Years`,
         grade = X2) %>% 
  unite(obs, grade, subj, sep = " ") %>% 
  mutate(obs = paste0(obs, " prof")) 

# we will add % with >95% attendance and pct with 0 suspensions (climate) 
# into the outcomes table, because it might be helpful to look at them together
climate <- demos %>% 
  slice(10:11) %>% 
  gather(year, pct, 2:5) %>% 
  mutate(obs = if_else(str_detect(X1, "Suspensions"), 
                       "0 suspensions", 
                       "95% attendance"),
         pct = as.numeric(str_replace(pct, "%", "")) * .01) %>% 
  select(-X1)

out <- bind_rows(out, climate)

# climate will remain separate because the unit of obervation is
# a referral, not a student
discipline <- demos %>% 
  slice(8:9) %>% 
  gather(year, value, 2:5) %>% 
  spread(X1, value) %>% 
  select(1,referrals = 2, pct_susp = 3) %>% 
  mutate(pct_susp = as.numeric(str_replace(pct_susp, "%", "")) * .01,
         suspension = as.numeric(referrals) * pct_susp) %>% 
  select(-pct_susp) %>% 
  gather(type, count, 2:3) %>% 
  mutate(count = as.numeric(count))

```


## Finding 1

Substantial changes in student population, 


```{r}
demos_tidy %>% 
  filter(!category %in% c("IEP", "ELLs")) %>% 
  group_by(year) %>% 
  summarise(total = sum(count)) %>% 
  ggplot(aes(x = year, y = total, group = 1)) + 
    geom_line(size = 2)
```


```{r}
demos_tidy %>% 
  filter(year %in% c("2013-2014", "2016-2017")) %>% 
  select(-pct, -total) %>% 
  spread(year, count) %>% 
  mutate(pct_change = (`2016-2017` - `2013-2014`) / `2013-2014`) %>% 
  ggplot(aes(category, pct_change)) +
    geom_bar(stat = "identity") + 
    scale_y_continuous(limits = c(-3, 3)) 
```

## Changes in climate

```{r}
discipline %>% 
  ggplot(aes(year, count, group = type, color = type)) + 
    geom_line(size = 2)
```


## Changes in outcomes
```{r}
out %>% 
  mutate(
    type = case_when(
      str_detect(obs, "reading") ~ "reading",
      str_detect(obs, "math") ~ "math",
      TRUE ~ "climate"),
    alpha = case_when(
     str_detect(obs, "6th") ~ 0,
     str_detect(obs, "7th") ~ .5,
     str_detect(obs, "8th") ~ 1,
     TRUE ~ 2)
  ) %>% 
  ggplot(aes(year, pct, group = obs, color = type, alpha = alpha)) + 
    geom_line(size = 2) 

```

```{r}
change_pct <- function(start, x) {
  x <- (x - start) / start
  x
}
  

out_wide <- out %>% 
  spread(year, pct)

out_wide[, 3:5] <- sapply(out_wide[, 3:5], function(x) {
  x <- change_pct(out_wide$`2013-2014`, x)
  x
})

out_wide$`2013-2014` <- 0

out_wide %>% 
  gather(year, pct_change, 2:5) %>% 
  ggplot(aes(year, pct_change)) +
    geom_line(aes(color = obs, group = obs), size = 2, alpha = 0.75) + 
    geom_smooth()
```


```{r}
out %>% 
  filter(year %in% c("2013-2014", "2016-2017")) %>% 
  spread(year, pct) %>% 
  mutate(pct_change = (`2016-2017` - `2013-2014`) / `2013-2014`) %>% 
  ggplot(aes(str_wrap(obs, 10), pct_change)) +
    geom_bar(stat = "identity")
```

## Model

```{r}

nested <- out %>% 
  separate(year, c("year1", "year2"), sep = "-", convert = TRUE) %>% 
  group_by(obs) %>% 
  nest()

obs_model <- function(df) {
  lm(pct ~ year1, data = df)
}

out_trends <- nested %>% 
  mutate(
    model = map(data, obs_model),
    residuals = map2(data, model, add_residuals) ,
    predictions = map2(data, model, add_predictions)
  )
    
out_trends %>% 
  unnest(predictions) %>% 
  ggplot(aes(year1, pred)) +
    geom_line(aes(group = obs, color = obs)) +
    geom_smooth()

out_trends %>% 
  unnest(residuals) %>% 
  ggplot(aes(year1, resid)) +
    geom_line(aes(group = obs, color = obs)) + 
    geom_smooth()

```

One hypothesis is that the changing demographics are affecting the outcomes.

Let's account for the percent of white students in our model to see if that changes things. 

```{r}
pct_white <- demos_tidy %>% 
  filter(category == "Black") %>% 
  select(year,
         pct_race = pct)

demos_out <- out %>% 
  left_join(pct_race, by = "year") %>% 
  separate(year, "year", sep = "-", convert = TRUE) %>% 
  group_by(obs) %>% 
  nest()

demos_model <- function(df) {
  lm(pct ~ pct_race, data = df)
}

demos_out %>% 
  mutate(
    model = map(data, demos_model),
    residuals = map2(data, model, add_residuals)
  ) %>% 
  unnest(residuals) %>% 
  ggplot(aes(year, resid)) + 
    geom_line(aes(group = obs)) + 
    geom_smooth()

```

Can we extend the same analysis for other categories? 

```{r}

demos_all <- demos_tidy %>% 
  select(year,
         category,
         pct_race = pct)

out_all_demos <- out %>% 
  left_join(demos_all, by = "year") %>% 
  separate(year, "year", sep = "-", convert = TRUE) %>% 
  group_by(category) %>% 
  nest()

demos_model2 <- function(df) {
  lm(pct ~ pct_race, data = df)
}

out_all_demos %>% 
  mutate(
    model = map(data, demos_model),
    residuals = map2(data, model, add_residuals),
    predictions = map2(data, model, add_predictions)
  ) %>% 
  unnest(residuals) %>% 
  unite(obs_cat, obs, category) %>% 
  ggplot(aes(year, resid)) +
    geom_line(aes(group = obs_cat), alpha = .25) +
    geom_smooth(se = FALSE) +
    geom_hline(yintercept = 0, color = "black", linetype = 2)

```

